name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Installing surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge --project ./ --token ${{secrets.SURGE_TOKEN}} --domain http://estefani-rafael-parcial1.surge.sh/

